/* ================================================================
   SIATIV — dadossiativ.js | banco de questões das Atividades
   ================================================================
   Uma lista de CONTEUDOS (um por simulador do 2º ano). Cada questão:
   q = enunciado · alts = 4 alternativas · ok = índice da correta ·
   exp = explicação exibida após responder. Valores e conceitos
   seguem exatamente os dados usados nos próprios simuladores.
   ================================================================ */
'use strict';

window.SIM_DATA = {
  ACRO: 'SIATIV',
  TITLE: 'Atividades dos Simuladores',

  CONTEUDOS: [
    {
      id: 'sigas', sigla: 'SIGAS', nome: 'Gases', sub: 'Leis, Clapeyron e Graham',
      desc: 'Questões sobre transformações gasosas, equação de Clapeyron e difusão — os três modos do SIGAS.',
      questoes: [
        { q: 'Num cilindro com pistão, um gás sofre transformação ISOTÉRMICA. Se o volume cair pela metade, a pressão…',
          alts: ['cai pela metade', 'dobra', 'não muda', 'quadruplica'], ok: 1,
          exp: 'Lei de Boyle: com T constante, P·V é constante — P e V são inversamente proporcionais. Metade do volume, o dobro da pressão.' },
        { q: 'Para usar as leis dos gases, a temperatura de 27 °C deve entrar nos cálculos como:',
          alts: ['27 K', '127 K', '300 K', '273 K'], ok: 2,
          exp: 'Temperatura sempre em kelvin: T(K) = t(°C) + 273 → 27 + 273 = 300 K.' },
        { q: 'Nas CNTP (0 °C e 1 atm), 1 mol de qualquer gás ideal ocupa aproximadamente:',
          alts: ['22,4 L', '1,0 L', '24,6 L', '760 L'], ok: 0,
          exp: 'Pela equação de Clapeyron: V = nRT/P = 1·0,082·273/1 ≈ 22,4 L — o volume molar nas CNTP.' },
        { q: 'Aquecer uma lata de aerossol fechada é perigoso porque, a volume constante, a pressão…',
          alts: ['diminui com T', 'cresce com a temperatura absoluta', 'independe de T', 'só depende do volume'], ok: 1,
          exp: 'Transformação isocórica (Gay-Lussac): P/T constante — a pressão cresce na mesma proporção da temperatura em kelvin.' },
        { q: 'Pela Lei de Graham, entre NH₃ (M = 17 g/mol) e HCl (M = 36,5 g/mol) liberados nas pontas de um tubo, o anel de NH₄Cl se forma:',
          alts: ['no meio exato do tubo', 'mais perto do lado do NH₃', 'mais perto do lado do HCl', 'fora do tubo'], ok: 2,
          exp: 'v ∝ 1/√M: a amônia, mais leve, anda mais rápido e percorre mais tubo; o encontro acontece mais perto do HCl, o gás lento.' },
      ],
    },
    {
      id: 'sisol', sigla: 'SISOL', nome: 'Soluções e Coligativas', sub: 'Concentração, diluição e efeitos',
      desc: 'Questões sobre preparo e diluição de soluções, curvas de solubilidade e propriedades coligativas — os seis modos do SISOL.',
      questoes: [
        { q: 'Dissolvendo 20 g de NaCl em água até completar 500 mL de solução, a concentração comum é:',
          alts: ['10 g/L', '20 g/L', '40 g/L', '4 g/L'], ok: 2,
          exp: 'C = m/V = 20 g / 0,5 L = 40 g/L. Atenção: o volume entra em litros.' },
        { q: 'Uma solução 2,0 g/L de KMnO₄ (100 mL) recebe água até 400 mL. A nova concentração é:',
          alts: ['0,5 g/L', '2,0 g/L', '8,0 g/L', '1,0 g/L'], ok: 0,
          exp: 'C₁V₁ = C₂V₂ → 2,0·100 = C₂·400 → C₂ = 0,5 g/L. Na diluição a massa de soluto não muda — só entra água.' },
        { q: 'A 20 °C a solubilidade do KNO₃ é ≈ 31,6 g/100 g de água. Adicionando 50 g de KNO₃ a 100 g de água nessa temperatura, a solução fica:',
          alts: ['insaturada', 'saturada sem excesso', 'saturada com corpo de fundo', 'supersaturada estável'], ok: 2,
          exp: 'Só ≈ 31,6 g dissolvem; os ≈ 18,4 g restantes não dissolvem e se depositam como corpo de fundo.' },
        { q: 'Comparando soluções aquosas 0,1 mol/kg de glicose (i = 1) e de CaCl₂ (i = 3), a que congela em temperatura MAIS BAIXA é:',
          alts: ['a de glicose', 'a de CaCl₂', 'as duas congelam igual', 'nenhuma congela'], ok: 1,
          exp: 'ΔTc = Kc·W·i: o CaCl₂ libera 3 partículas por fórmula (Ca²⁺ + 2 Cl⁻), triplicando o efeito crioscópico.' },
        { q: 'Na osmose, a água atravessa a membrana semipermeável no sentido:',
          alts: ['do meio mais concentrado para o menos', 'do meio menos concentrado para o mais concentrado', 'dos dois lados igualmente, sempre', 'apenas se houver pressão externa'], ok: 1,
          exp: 'O solvente flui do meio hipotônico para o hipertônico, tentando igualar as concentrações — por isso soro precisa ser isotônico.' },
      ],
    },
    {
      id: 'sitq', sigla: 'SITQ', nome: 'Termoquímica', sub: 'Calor, ΔH e Lei de Hess',
      desc: 'Questões sobre calorimetria, mudanças de fase, diagramas de energia e Lei de Hess — os modos do SITQ.',
      questoes: [
        { q: 'Numa reação EXOTÉRMICA, o sinal do ΔH e a temperatura da vizinhança são:',
          alts: ['ΔH > 0 e a vizinhança esfria', 'ΔH < 0 e a vizinhança esquenta', 'ΔH < 0 e a vizinhança esfria', 'ΔH > 0 e a vizinhança esquenta'], ok: 1,
          exp: 'Exotérmica libera calor: a entalpia dos produtos é menor (ΔH negativo) e o ambiente ao redor aquece.' },
        { q: 'O calor para aquecer 200 g de água (c = 4,186 J/g·°C) de 20 °C a 70 °C é, aproximadamente:',
          alts: ['≈ 42 kJ', '≈ 4,2 kJ', '≈ 419 kJ', '≈ 8,4 kJ'], ok: 0,
          exp: 'Q = m·c·ΔT = 200 · 4,186 · 50 ≈ 41.860 J ≈ 42 kJ.' },
        { q: 'Na curva de aquecimento da água, durante a fusão do gelo a temperatura:',
          alts: ['sobe rapidamente', 'fica constante em 0 °C', 'cai um pouco', 'sobe até 100 °C'], ok: 1,
          exp: 'Nos patamares o calor recebido é calor LATENTE: rompe a organização do sólido sem elevar a temperatura.' },
        { q: 'O catalisador, num diagrama de energia, altera:',
          alts: ['o ΔH da reação', 'a energia dos produtos', 'apenas a energia de ativação', 'a quantidade de produto formado'], ok: 2,
          exp: 'Catalisador abre um caminho de menor Ea — acelera a reação, mas ΔH e rendimento continuam os mesmos.' },
        { q: 'A Lei de Hess permite calcular o ΔH de uma reação porque a entalpia:',
          alts: ['depende do caminho seguido', 'é função de estado: só importam início e fim', 'é sempre positiva', 'só existe em reações de combustão'], ok: 1,
          exp: 'Sendo função de estado, o ΔH total é a soma dos ΔH das etapas — não importa o percurso entre reagentes e produtos.' },
      ],
    },
    {
      id: 'sicin', sigla: 'SICIN', nome: 'Cinética Química', sub: 'Colisões, curvas e Ea',
      desc: 'Questões sobre teoria das colisões, fatores de velocidade e energia de ativação — os modos do SICIN.',
      questoes: [
        { q: 'Pela teoria das colisões, uma colisão só é EFETIVA quando:',
          alts: ['as moléculas apenas se tocam', 'há energia acima da Ea e orientação adequada', 'a temperatura é baixa', 'existe catalisador presente'], ok: 1,
          exp: 'São as duas exigências simultâneas: energia mínima (≥ Ea) e geometria de choque favorável.' },
        { q: 'Palha de aço enferruja mais rápido que um prego de mesma massa porque:',
          alts: ['tem maior superfície de contato', 'o ferro é diferente', 'a Ea diminui', 'o ΔH muda'], ok: 0,
          exp: 'Mais superfície exposta = mais choques por segundo com o O₂ — a frequência de colisões aumenta.' },
        { q: 'Aumentar a temperatura acelera uma reação principalmente porque:',
          alts: ['diminui a energia de ativação', 'aumenta a fração de moléculas com energia acima da Ea', 'reduz a concentração', 'muda o estado físico'], ok: 1,
          exp: 'Na distribuição de Maxwell-Boltzmann, mais T desloca a curva: cresce a área além da Ea — mais choques efetivos.' },
        { q: 'Numa reação de 1ª ordem com meia-vida de 20 s e [A]₀ = 1,0 mol/L, após 40 s a concentração de A é:',
          alts: ['0,50 mol/L', '0,25 mol/L', '0,10 mol/L', 'zero'], ok: 1,
          exp: '40 s = 2 meias-vidas: 1,0 → 0,50 → 0,25 mol/L. Em 1ª ordem, t½ não depende da concentração.' },
        { q: 'O catalisador acelera a reação porque:',
          alts: ['é consumido fornecendo energia', 'aumenta a temperatura do meio', 'oferece um caminho alternativo de menor Ea', 'aumenta o ΔH'], ok: 2,
          exp: 'Ele participa do mecanismo e é regenerado no fim; só a barreira (Ea) diminui — ΔH permanece igual.' },
      ],
    },
    {
      id: 'sieq', sigla: 'SIEQ', nome: 'Equilíbrio e pH', sub: 'Le Chatelier, Q×K e titulação',
      desc: 'Questões sobre equilíbrio químico, Le Chatelier, quociente Q, escala de pH e titulação — os seis modos do SIEQ.',
      questoes: [
        { q: 'No equilíbrio químico dinâmico, o que fica igual são:',
          alts: ['as concentrações de reagentes e produtos', 'as velocidades das reações direta e inversa', 'as massas de todas as espécies', 'os coeficientes da equação'], ok: 1,
          exp: 'v_direta = v_inversa: as concentrações ficam CONSTANTES (não necessariamente iguais) porque as duas reações continuam ocorrendo.' },
        { q: 'Para N₂O₄(g) ⇌ 2 NO₂(g), reduzir o volume do frasco desloca o equilíbrio:',
          alts: ['para o NO₂ (mais mols de gás)', 'para o N₂O₄ (menos mols de gás)', 'não desloca', 'depende do catalisador'], ok: 1,
          exp: 'Comprimir favorece o lado com MENOS mols gasosos (1 mol de N₂O₄ contra 2 de NO₂), atenuando o aumento de pressão.' },
        { q: 'Se em dado instante Q < Kc, o sistema:',
          alts: ['já está em equilíbrio', 'caminha formando mais produtos', 'caminha formando mais reagentes', 'para de reagir'], ok: 1,
          exp: 'Q menor que K indica produtos "de menos": a reação avança para a direita até Q igualar Kc.' },
        { q: 'Uma solução de pH 3 comparada a outra de pH 5 é:',
          alts: ['2 vezes mais ácida', '10 vezes mais ácida', '100 vezes mais ácida', 'mais básica'], ok: 2,
          exp: 'pH é escala logarítmica: cada unidade vale 10× — duas unidades valem 10² = 100 vezes mais H₃O⁺.' },
        { q: 'Na titulação de 25 mL de HCl 0,100 mol/L com NaOH 0,100 mol/L, o ponto de equivalência ocorre com:',
          alts: ['12,5 mL de base e pH 7', '25 mL de base e pH 7', '25 mL de base e pH 9', '50 mL de base e pH 1'], ok: 1,
          exp: 'n_ácido = n_base → mesmos C e V: 25 mL. Ácido forte + base forte → sal neutro: pH 7 no salto da curva.' },
      ],
    },
    {
      id: 'sielq', sigla: 'SIELQ', nome: 'Eletroquímica', sub: 'Pilhas, eletrólise e Faraday',
      desc: 'Questões sobre pilhas, potenciais padrão, espontaneidade, eletrólise e leis de Faraday — os seis modos do SIELQ.',
      questoes: [
        { q: 'Na pilha de Daniell (E° Zn²⁺/Zn = −0,76 V; E° Cu²⁺/Cu = +0,34 V), o ânodo e a ddp são:',
          alts: ['cobre; 1,10 V', 'zinco; 1,10 V', 'zinco; 0,42 V', 'cobre; −1,10 V'], ok: 1,
          exp: 'Menor potencial de redução oxida: o zinco é o ânodo. ΔE° = 0,34 − (−0,76) = 1,10 V.' },
        { q: 'Numa pilha em funcionamento, os elétrons percorrem o fio externo:',
          alts: ['do cátodo para o ânodo', 'do ânodo para o cátodo', 'nos dois sentidos', 'pela ponte salina'], ok: 1,
          exp: 'Elétrons nascem na oxidação (ânodo, polo −) e fluem ao cátodo (polo +). A ponte salina conduz íons, não elétrons.' },
        { q: 'Uma fita de zinco mergulhada em solução azul de CuSO₄:',
          alts: ['nada acontece', 'escurece, depositando cobre, e o azul empalidece', 'dissolve o cobre metálico', 'libera gás oxigênio'], ok: 1,
          exp: 'Zn (E° menor) desloca o Cu²⁺: Zn → Zn²⁺ + 2e⁻ e Cu²⁺ + 2e⁻ → Cu. Reação espontânea, ΔE° > 0.' },
        { q: 'Na eletrólise ígnea do NaCl fundido, forma-se no CÁTODO:',
          alts: ['gás cloro', 'sódio metálico', 'gás hidrogênio', 'hidróxido de sódio'], ok: 1,
          exp: 'No cátodo ocorre REDUÇÃO do cátion: Na⁺ + e⁻ → Na(l). O Cl₂ aparece no ânodo. Sem água, não há H₂.' },
        { q: 'Quantos mols de elétrons (F = 96.500 C/mol) depositam 1 mol de prata (Ag⁺ + e⁻ → Ag)?',
          alts: ['1 mol', '2 mols', '0,5 mol', '96.500 mols'], ok: 0,
          exp: 'Cada Ag⁺ precisa de 1 elétron: 1 mol de Ag exige 1 mol de e⁻ = 1 faraday = 96.500 C de carga.' },
      ],
    },
    {
      id: 'sirad', sigla: 'SIRAD', nome: 'Radioatividade', sub: 'Emissões, meia-vida e fissão',
      desc: 'Questões sobre as emissões α, β e γ, decaimento com meia-vida e fissão nuclear — os modos do SIRAD.',
      questoes: [
        { q: 'A radiação mais PENETRANTE, atenuada apenas por chumbo ou concreto espessos, é a:',
          alts: ['alfa', 'beta', 'gama', 'catódica'], ok: 2,
          exp: 'γ é onda eletromagnética sem carga nem massa: atravessa papel e alumínio; α para no papel e β no alumínio.' },
        { q: 'Ao emitir uma partícula ALFA (₂⁴α), o núcleo tem seu número atômico e sua massa alterados em:',
          alts: ['Z − 2 e A − 4', 'Z + 1 e A constante', 'Z − 1 e A − 2', 'Z e A constantes'], ok: 0,
          exp: '1ª Lei de Soddy: a partícula α leva 2 prótons e 2 nêutrons — o elemento recua duas casas na tabela.' },
        { q: 'O iodo-131 tem meia-vida de ≈ 8 dias. De 80 g iniciais, após 24 dias restam:',
          alts: ['40 g', '20 g', '10 g', '0 g'], ok: 2,
          exp: '24 dias = 3 meias-vidas: 80 → 40 → 20 → 10 g. N = N₀·(1/2)ⁿ.' },
        { q: 'A datação por carbono-14 (t½ = 5.730 anos) funciona porque, após a morte do organismo:',
          alts: ['o ¹⁴C começa a se formar', 'o ¹⁴C para de ser reposto e só decai', 'o ¹²C decai rapidamente', 'a meia-vida muda com o ambiente'], ok: 1,
          exp: 'Vivo, o ser troca carbono com o ambiente; morto, o ¹⁴C só diminui — a fração restante revela o tempo decorrido.' },
        { q: 'Numa reação de fissão em cadeia, o regime SUPERCRÍTICO acontece quando cada fissão provoca, em média:',
          alts: ['menos de 1 nova fissão', 'exatamente 1 nova fissão', 'mais de 1 nova fissão', 'nenhum nêutron novo'], ok: 2,
          exp: 'k > 1: o número de fissões cresce em avalanche. Reatores operam em k ≈ 1 (crítico) usando barras de controle.' },
      ],
    },
  ],

  CURIOSIDADES: [
    'Errar faz parte: rever a explicação de uma questão errada fixa mais que acertar de primeira.',
    'Cada bloco embaralha as questões a cada tentativa — refaça para treinar de verdade, não para decorar posições.',
    'As alternativas usam os MESMOS números e substâncias dos simuladores: volte a eles para conferir qualquer resposta.',
    'Prefira responder sem calculadora: as contas foram escolhidas para fechar de cabeça.',
    'Aproveitamento acima de 80 % num conteúdo é sinal verde para avançar ao próximo simulador.',
  ],
};
