/* ================================================================
   SISOL — dadossolucoes.js | dados fixos de Soluções e Coligativas
   ================================================================
   FONTES: solubilidades e massas molares — CRC Handbook of Chemistry
   & Physics; Wikipedia/CRC (NH₄NO₃, KCl, KBr, KI, NaNO₃, Pb(NO₃)₂,
   (NH₄)₂SO₄, K₂Cr₂O₇, NaBr); tabelas didáticas (Usberco & Salvador;
   Feltre). Pressão de vapor — equação de Antoine com coeficientes
   NIST WebBook / Yaws (Chemical Properties Handbook) para água,
   etanol, metanol, acetona, benzeno, tolueno, hexano, clorofórmio e
   isopropanol; éter etílico por tabela CRC (equação de Antoine
   publicada tem baixa precisão nessa faixa). Ke/Kc — Atkins & de
   Paula; Chang; Wikipedia "Ebullioscopic/Cryoscopic constant" (água,
   benzeno, ácido acético, cânfora, CCl₄, ciclohexano — os dois
   últimos com Kf grandes, atrás só da cânfora). Fator de van 't Hoff
   — estequiometria de dissociação de cada eletrólito. π = MRT com
   R = 0,082 atm·L·mol⁻¹·K⁻¹. Lei de Henry — constantes de
   solubilidade de gases a 25 °C: Sander, R., "Compilation of
   Henry's Law Constants" (Atmos. Chem. Phys., 2015), para CO₂, O₂,
   N₂, Ar, CH₄ e H₂; dependência com T calibrada pelo fato
   documentado de que a solubilidade do N₂ cai a ≈43% entre 25 °C e
   95 °C (mesma fonte). Misturas do dia a dia — classificação por
   tamanho de partícula, padrão de livros-texto (OpenStax/LibreTexts).
   ================================================================ */
'use strict';

window.SIM_DATA = {
  ACRO: 'SISOL',
  TITLE: 'Simulador Interativo de Soluções e Propriedades Coligativas',

  /* ── Misturas do dia a dia para o modo "Classificação de Misturas" ──
        Classificação por tamanho de partícula dispersa (padrão consagrado
        em livros-texto de química geral / OpenStax / LibreTexts):
        solução verdadeira <1 nm (feixe de luz não se espalha), colóide
        1–1000 nm (efeito Tyndall: o feixe se torna visível, mas não
        sedimenta), suspensão >1000 nm (sedimenta com o tempo, pode ser
        filtrada). ── */
  MISTURAS: [
    { id: 'salmoura', nome: 'Água + sal de cozinha', tipo: 'solucao', cor: '#38bdf8',
      contexto: 'o NaCl se dissocia em íons Na⁺ e Cl⁻, partículas menores que 1 nm — pequenas demais para espalhar luz.' },
    { id: 'acucar', nome: 'Água + açúcar', tipo: 'solucao', cor: '#38bdf8',
      contexto: 'as moléculas de sacarose ficam dispersas a nível molecular, então a mistura fica sempre transparente.' },
    { id: 'ar', nome: 'Ar atmosférico', tipo: 'solucao', cor: '#cbd5e1',
      contexto: 'gases se misturam completamente a nível molecular — uma solução gasosa.' },
    { id: 'vinagre', nome: 'Vinagre (água + ácido acético)', tipo: 'solucao', cor: '#fef3c7',
      contexto: 'o ácido acético se dissolve completamente em água a nível molecular, sem nenhuma partícula visível.' },
    { id: 'aguagas', nome: 'Água mineral com gás', tipo: 'solucao', cor: '#e0f2fe',
      contexto: 'o CO₂ dissolvido fica em nível molecular — as bolhas só aparecem quando o gás em excesso escapa, não são o "soluto disperso".' },
    { id: 'alcool70', nome: 'Álcool 70% (etanol + água)', tipo: 'solucao', cor: '#dbeafe',
      contexto: 'etanol e água são totalmente miscíveis, misturando-se a nível molecular — o antisséptico caseiro mais comum.' },
    { id: 'latao', nome: 'Latão (liga de cobre e zinco)', tipo: 'solucao', cor: '#facc15',
      contexto: 'uma "solução sólida": átomos de zinco ficam dispersos na rede cristalina do cobre, nível atômico.' },
    { id: 'muriatico', nome: 'Ácido muriático diluído', tipo: 'solucao', cor: '#fef9c3',
      contexto: 'HCl gasoso dissolvido em água, dissociado em H⁺ e Cl⁻ — íons pequenos demais para espalhar luz.' },
    { id: 'sorofis', nome: 'Soro fisiológico', tipo: 'solucao', cor: '#f0f9ff',
      contexto: 'solução de NaCl a 0,9% — mesma salinidade do plasma sanguíneo, sempre transparente.' },
    { id: 'tinturaiodo', nome: 'Tintura de iodo (iodo em álcool)', tipo: 'solucao', cor: '#7c2d12',
      contexto: 'o iodo se dissolve molecularmente no álcool — a cor vem da própria molécula de I₂, não de partículas dispersas.' },
    { id: 'aguaoxigenada', nome: 'Água oxigenada', tipo: 'solucao', cor: '#e0f2fe',
      contexto: 'H₂O₂ dissolvido em água a nível molecular — solução sempre transparente.' },
    { id: 'amoniadom', nome: 'Amônia doméstica (NH₃ em água)', tipo: 'solucao', cor: '#ecfeff',
      contexto: 'o gás amônia se dissolve completamente em água, a nível molecular — produto de limpeza comum.' },
    { id: 'xarope', nome: 'Xarope simples (água + açúcar concentrado)', tipo: 'solucao', cor: '#fef3c7',
      contexto: 'mesmo bem concentrada, a sacarose continua dispersa a nível molecular — só fica mais viscosa, não turva.' },
    { id: 'aco', nome: 'Aço inoxidável (liga Fe-Cr-Ni)', tipo: 'solucao', cor: '#94a3b8',
      contexto: 'outra "solução sólida": átomos de cromo e níquel dispersos na rede cristalina do ferro.' },
    { id: 'leite', nome: 'Leite', tipo: 'coloide', cor: '#f8fafc', dot: '#fef9c3',
      contexto: 'gotículas de gordura (10–1000 nm) dispersas em água — grandes o bastante para espalhar luz, mas pequenas demais para sedimentar sozinhas.' },
    { id: 'neblina', nome: 'Neblina', tipo: 'coloide', cor: '#e2e8f0', dot: '#f1f5f9',
      contexto: 'gotículas de água dispersas no ar — um aerossol líquido, mesmo princípio do leite.' },
    { id: 'fumaca', nome: 'Fumaça', tipo: 'coloide', cor: '#94a3b8', dot: '#475569',
      contexto: 'partículas sólidas de carbono dispersas no ar — um aerossol sólido.' },
    { id: 'maionese', nome: 'Maionese', tipo: 'coloide', cor: '#fef3c7', dot: '#fde68a',
      contexto: 'emulsão de gotículas de óleo em água, estabilizada pela lecitina do ovo.' },
    { id: 'manteiga', nome: 'Manteiga', tipo: 'coloide', cor: '#fde68a', dot: '#fbbf24',
      contexto: 'o inverso da maionese: gotículas de água dispersas na gordura — outra emulsão, com as fases trocadas.' },
    { id: 'gelatina', nome: 'Gelatina (já firme)', tipo: 'coloide', cor: '#fca5a5', dot: '#f87171',
      contexto: 'um "gel": a fase dispersa (proteína) forma uma rede que aprisiona o líquido — um colóide sólido-em-líquido.' },
    { id: 'espumabarbear', nome: 'Espuma de barbear', tipo: 'coloide', cor: '#f8fafc', dot: '#e2e8f0',
      contexto: 'bolhas de gás dispersas num líquido (espuma) — partículas grandes o bastante pra espalhar luz, mas sem sedimentar.' },
    { id: 'cremedental', nome: 'Creme dental', tipo: 'coloide', cor: '#e0f2fe', dot: '#bae6fd',
      contexto: 'partículas sólidas abrasivas dispersas num gel — pequenas demais pra sedimentar sozinhas em pouco tempo.' },
    { id: 'poeira', nome: 'Poeira fina no ar', tipo: 'coloide', cor: '#d6d3d1', dot: '#a8a29e',
      contexto: 'partículas sólidas finas (1–1000 nm) suspensas no ar — por isso ficam pairando por horas antes de assentar.' },
    { id: 'claraovo', nome: 'Clara de ovo', tipo: 'coloide', cor: '#f8fafc', dot: '#fefce8',
      contexto: 'moléculas de albumina (proteína) dispersas em água — grandes o bastante pra espalhar luz de leve.' },
    { id: 'gelcabelo', nome: 'Gel de cabelo', tipo: 'coloide', cor: '#a7f3d0', dot: '#6ee7b7',
      contexto: 'polímero disperso em água formando uma rede — mesma lógica da gelatina, com outro composto.' },
    { id: 'detergente', nome: 'Detergente/sabão líquido', tipo: 'coloide', cor: '#bae6fd', dot: '#7dd3fc',
      contexto: 'moléculas de tensoativo se agrupam em micelas (agregados de 1–10 nm) — grandes o bastante pra dar o efeito Tyndall.' },
    { id: 'protetorsolar', nome: 'Protetor solar físico', tipo: 'coloide', cor: '#fef9c3', dot: '#fef08a',
      contexto: 'partículas de óxido de zinco/titânio dispersas no creme — pequenas o bastante pra não sedimentar rápido.' },
    { id: 'iogurte', nome: 'Iogurte natural', tipo: 'coloide', cor: '#f8fafc', dot: '#f1f5f9',
      contexto: 'proteínas do leite coaguladas formam uma rede coloidal que aprisiona o soro — parecido com a gelatina.' },
    { id: 'espumacerveja', nome: 'Espuma de cerveja/chope', tipo: 'coloide', cor: '#fef3c7', dot: '#fde68a',
      contexto: 'bolhas de CO₂ dispersas no líquido, estabilizadas por proteínas — outra espuma coloidal.' },
    { id: 'vitral', nome: 'Vidro colorido (vitral)', tipo: 'coloide', cor: '#f87171', dot: '#dc2626',
      contexto: 'nanopartículas metálicas dispersas na rede do vidro — um colóide sólido-em-sólido, cor vem do tamanho da partícula.' },
    { id: 'areia', nome: 'Água + areia', tipo: 'suspensao', cor: '#d6d3d1', dot: '#a8a29e',
      contexto: 'grãos de areia (maiores que 1000 nm, visíveis a olho nu) sedimentam rápido e podem ser filtrados.' },
    { id: 'giz', nome: 'Água + pó de giz', tipo: 'suspensao', cor: '#f5f5f4', dot: '#e7e5e4',
      contexto: 'partículas de carbonato de cálcio grandes demais para ficarem dispersas — sedimentam com o tempo.' },
    { id: 'suco', nome: 'Suco de laranja com polpa', tipo: 'suspensao', cor: '#fb923c', dot: '#f97316',
      contexto: 'as fibras da polpa são grandes o bastante para sedimentar no fundo do copo se ele ficar parado.' },
    { id: 'leitemagnesia', nome: 'Leite de magnésia', tipo: 'suspensao', cor: '#f8fafc', dot: '#e2e8f0',
      contexto: 'cristais de Mg(OH)₂ ficam suspensos e sedimentam se o frasco descansar — por isso a bula manda "agitar antes de usar".' },
    { id: 'aguabarrenta', nome: 'Água barrenta de rio', tipo: 'suspensao', cor: '#d6a06d', dot: '#92400e',
      contexto: 'partículas de argila e silte grandes o bastante para turvar a água e sedimentar com o tempo (decantação).' },
    { id: 'guache', nome: 'Tinta guache', tipo: 'suspensao', cor: '#60a5fa', dot: '#2563eb',
      contexto: 'pigmento sólido disperso em água — sedimenta no pote se ficar parado tempo demais, por isso precisa agitar.' },
    { id: 'chafolhas', nome: 'Chá com folhas soltas', tipo: 'suspensao', cor: '#a16207', dot: '#78350f',
      contexto: 'fragmentos de folha são grandes o bastante para sedimentar no fundo da xícara — por isso se usa coador.' },
    { id: 'contrastebario', nome: 'Suspensão de sulfato de bário (contraste)', tipo: 'suspensao', cor: '#f8fafc', dot: '#cbd5e1',
      contexto: 'partículas de BaSO₄ ficam suspensas só temporariamente — por isso o exame de contraste é tomado pouco antes do procedimento.' },
    { id: 'maisena', nome: 'Água + amido de milho (maisena)', tipo: 'suspensao', cor: '#fefce8', dot: '#fef08a',
      contexto: 'grânulos de amido são grandes o bastante pra sedimentar no fundo do copo se ficar parado.' },
    { id: 'caldabordalesa', nome: 'Calda bordalesa (fungicida agrícola)', tipo: 'suspensao', cor: '#60a5fa', dot: '#1d4ed8',
      contexto: 'sulfato de cobre e cal formam partículas grandes suspensas — por isso precisa agitar o pulverizador sem parar.' },
    { id: 'carvaoativado', nome: 'Água + carvão ativado em pó', tipo: 'suspensao', cor: '#57534e', dot: '#292524',
      contexto: 'partículas de carvão são grandes o bastante pra turvar a água e sedimentar, mesmo sendo um pó bem fino.' },
    { id: 'cimento', nome: 'Cimento fresco (antes de curar)', tipo: 'suspensao', cor: '#d6d3d1', dot: '#a8a29e',
      contexto: 'partículas minerais grandes suspensas em água — sedimentam e endurecem se a mistura descansar demais.' },
    { id: 'suconatural', nome: 'Suco natural batido com bagaço', tipo: 'suspensao', cor: '#fb923c', dot: '#c2410c',
      contexto: 'pedaços de fibra da fruta são grandes o bastante pra sedimentar no fundo do copo em minutos.' },
    { id: 'bentonita', nome: 'Suspensão de argila bentonita', tipo: 'suspensao', cor: '#d6d3d1', dot: '#78716c',
      contexto: 'partículas de argila usadas em perfuração — ficam suspensas por agitação, mas sedimentam em repouso.' },
    { id: 'aguaesponja', nome: 'Água de esfregar chão (com sujeira)', tipo: 'suspensao', cor: '#78716c', dot: '#44403c',
      contexto: 'partículas sólidas de sujeira grandes o bastante pra turvar e sedimentar no balde parado.' },
    { id: 'iogurtefruta', nome: 'Iogurte com pedaços de fruta', tipo: 'suspensao', cor: '#fda4af', dot: '#e11d48',
      contexto: 'os pedaços de fruta (bem maiores que 1000 nm) sedimentam no fundo do pote — diferente do colóide do iogurte puro.' },
    { id: 'oleovinagre', nome: 'Molho de óleo e vinagre (sem emulsificar)', tipo: 'suspensao', cor: '#fde047', dot: '#ca8a04',
      contexto: 'gotas de óleo grandes se separam e "sedimentam" (flutuam) rápido — por isso teve de agitar antes de servir.' },
    { id: 'sangue', nome: 'Sangue total (com hemácias)', tipo: 'suspensao', cor: '#dc2626', dot: '#7f1d1d',
      contexto: 'as hemácias (≈7000 nm) são grandes o bastante pra sedimentar quando centrifugadas — por isso o sangue "separa" em plasma e células.' },
    { id: 'tintagraffiti', nome: 'Tinta spray recém-agitada', tipo: 'suspensao', cor: '#22d3ee', dot: '#0891b2',
      contexto: 'pigmento sólido disperso no solvente — por isso a lata pede pra "agitar bem antes de usar", senão o pigmento sedimenta.' },
    { id: 'aguacacau', nome: 'Achocolatado em pó mal dissolvido', tipo: 'suspensao', cor: '#78350f', dot: '#451a03',
      contexto: 'partículas de cacau e açúcar que não dissolveram ficam grandes o bastante pra sedimentar no fundo do copo.' },
  ],

  /* ── Solutos do modo Preparo — cada um agora tem uma CURVA completa de
        solubilidade (g/100 g de água, T = 0…100 °C, passo 10), a mesma
        base das 7 curvas do modo "Curvas de Solubilidade" + 3 adicionais
        (sacarose, CuSO₄, KMnO₄) com valores aproximados de tabelas
        didáticas/CRC — isso permite o slider de temperatura do preparo
        influenciar o limite de solubilidade real, junto com massa e
        volume, em vez de um único valor fixo a 25 °C. ── */
  SOLUTOS: [
    { id: 'nacl',   nome: 'NaCl (sal de cozinha)', M: 58.44,  cor: null,      dot: '#e2e8f0',
      curva: [35.7, 35.8, 36.0, 36.3, 36.6, 37.0, 37.3, 37.8, 38.4, 39.0, 39.8] },
    { id: 'sacar',  nome: 'Sacarose C₁₂H₂₂O₁₁',    M: 342.30, cor: null,      dot: '#fde8c8',
      curva: [179, 190, 204, 219, 238, 260, 287, 320, 362, 415, 487] },
    { id: 'kno3',   nome: 'KNO₃ (salitre)',        M: 101.10, cor: null,      dot: '#f1f5f9',
      curva: [13.3, 20.9, 31.6, 45.8, 63.9, 85.5, 110, 138, 169, 202, 246] },
    { id: 'cuso4',  nome: 'CuSO₄ (anidro)',        M: 159.61, cor: '#2f7fd6', dot: '#3b82f6',
      curva: [14.3, 17.4, 20.7, 25.0, 28.5, 33.3, 40.0, 47.0, 56.0, 67.0, 80.0] },
    { id: 'kmno4',  nome: 'KMnO₄',                 M: 158.03, cor: '#7e22ce', dot: '#9333ea',
      curva: [2.8, 4.3, 6.4, 9.0, 12.6, 16.1, 22.2, 28.4, 36.4, 45.0, 55.0] },
    { id: 'nh4no3', nome: 'NH₄NO₃',                M: 80.04,  cor: null,      dot: '#fdba74',
      curva: [118, 150, 192, 230, 297, 350, 410, 490, 576, 780, 1024] },
    { id: 'nh4cl',  nome: 'NH₄Cl',                 M: 53.49,  cor: null,      dot: '#a5f3fc',
      curva: [29.4, 33.3, 37.2, 41.4, 45.8, 50.4, 55.2, 60.2, 65.6, 71.3, 77.3] },
    { id: 'kclo3',  nome: 'KClO₃',                 M: 122.55, cor: null,      dot: '#fbcfe8',
      curva: [3.3, 5.0, 7.4, 10.5, 14.0, 19.3, 24.5, 31.5, 38.5, 46.7, 56.2] },
    { id: 'na2so4', nome: 'Na₂SO₄',                M: 142.04, cor: null,      dot: '#e9d5ff',
      curva: [4.8, 9.1, 19.5, 40.8, 48.8, 46.7, 45.3, 44.3, 43.7, 42.9, 42.5] },
    { id: 'li2so4', nome: 'Li₂SO₄',                M: 109.94, cor: null,      dot: '#cbd5e1',
      curva: [36.1, 35.5, 34.8, 34.2, 33.7, 33.1, 32.6, 32.1, 31.6, 31.0, 30.9] },
    { id: 'kcl',    nome: 'KCl',                   M: 74.55,  cor: null,      dot: '#dbeafe',
      curva: [27.6, 31.0, 34.0, 37.0, 40.0, 42.6, 45.5, 48.3, 51.1, 54.0, 56.7] },
    { id: 'kbr',    nome: 'KBr',                   M: 119.00, cor: null,      dot: '#99f6e4',
      curva: [53.5, 59.5, 65.2, 70.6, 75.5, 80.2, 85.5, 90.0, 95.0, 99.2, 104] },
    { id: 'ki',     nome: 'KI',                    M: 166.00, cor: null,      dot: '#fecdd3',
      curva: [128, 136, 144, 153, 162, 172, 182, 192, 202, 212, 222] },
    { id: 'nano3',  nome: 'NaNO₃',                 M: 85.00,  cor: null,      dot: '#f5d0fe',
      curva: [73, 80, 88, 96, 104, 114, 124, 135, 148, 162, 180] },
    { id: 'pbno32', nome: 'Pb(NO₃)₂',              M: 331.20, cor: null,      dot: '#fef08a',
      curva: [38, 46, 54, 63, 72, 80, 90, 100, 110, 121, 133] },
    { id: 'nh42so4', nome: '(NH₄)₂SO₄',            M: 132.14, cor: null,      dot: '#d9f99d',
      curva: [70.6, 73.0, 75.4, 78.0, 81.0, 84.5, 88.0, 92.0, 95.0, 98.0, 103] },
    { id: 'k2cr2o7', nome: 'K₂Cr₂O₇ (dicromato)',  M: 294.18, cor: '#dc2626', dot: '#fca5a5',
      curva: [4.9, 7.4, 12.3, 18.1, 25.2, 33.2, 45.6, 59.8, 73.0, 87.1, 102] },
    { id: 'nabr',   nome: 'NaBr',                  M: 102.89, cor: null,      dot: '#bae6fd',
      curva: [79.5, 85, 88, 90, 92, 95, 99, 104, 108, 114, 121] },
    { id: 'naf',    nome: 'NaF',                   M: 41.99,  cor: null,      dot: '#a5f3fc',
      curva: [3.7, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0, 5.1, 5.2, 5.3, 5.4] },
    { id: 'licl',   nome: 'LiCl',                  M: 42.39,  cor: null,      dot: '#fde68a',
      curva: [63.7, 67.2, 69.2, 74.5, 79.8, 85.2, 89.8, 91.3, 93.2, 95.5, 98.3] },
    { id: 'nai',    nome: 'NaI',                   M: 149.89, cor: null,      dot: '#c7d2fe',
      curva: [159, 167, 175, 184, 191, 199, 207, 225, 275, 295, 302] },
    { id: 'agno3',  nome: 'AgNO₃',                 M: 169.87, cor: '#78716c', dot: '#e5e7eb',
      curva: [122, 170, 216, 256, 300, 376, 440, 525, 585, 733, 952] },
    { id: 'k2co3',  nome: 'K₂CO₃',                 M: 138.21, cor: null,      dot: '#fde68a',
      curva: [105, 108, 111, 114, 117, 121, 126, 132, 138, 144, 151] },
    { id: 'bacl2',  nome: 'BaCl₂',                 M: 208.23, cor: null,      dot: '#fca5a5',
      curva: [31.2, 33.3, 35.6, 37.8, 40.2, 42.9, 46.2, 49.4, 52.4, 55.8, 59.4] },
    { id: 'nh4br',  nome: 'NH₄Br',                 M: 97.94,  cor: null,      dot: '#a5f3fc',
      curva: [60, 68, 76, 83, 91, 99, 108, 117, 126, 135, 145] },
    { id: 'cucl2',  nome: 'CuCl₂',                 M: 134.45, cor: '#0891b2', dot: '#22d3ee',
      curva: [68.6, 70.9, 73.0, 74.5, 76.7, 79.2, 81.4, 84.4, 87.6, 91.2, 96.5] },
    { id: 'niso4',  nome: 'NiSO₄',                 M: 154.75, cor: '#84cc16', dot: '#bef264',
      curva: [26.6, 33.2, 38.4, 43.5, 47.9, 51.3, 34.5, 30.9, 30.0, 29.4, 28.9] },
    { id: 'mncl2',  nome: 'MnCl₂',                 M: 125.84, cor: '#fb7185', dot: '#fda4af',
      curva: [63.4, 68.1, 73.9, 77.3, 80.6, 84.0, 87.8, 92.9, 98.1, 100.5, 102.7] },
    { id: 'cabr2',  nome: 'CaBr₂',                 M: 199.89, cor: null,      dot: '#fecaca',
      curva: [125, 132, 137, 143, 150, 158, 168, 180, 195, 210, 230] },
    { id: 'srcl2',  nome: 'SrCl₂',                 M: 158.53, cor: null,      dot: '#fdba74',
      curva: [43.5, 46.5, 50.5, 53.8, 59.7, 66.4, 77.0, 91.0, 96.5, 100.8, 104.9] },
    { id: 'cocl2',  nome: 'CoCl₂',                 M: 129.84, cor: '#60a5fa', dot: '#93c5fd',
      curva: [43.5, 47.7, 52.9, 66.8, 84.9, 90.5, 95.6, 97.9, 99.1, 100.9, 105.8] },
    { id: 'coso4',  nome: 'CoSO₄',                 M: 155.00, cor: '#f472b6', dot: '#fbcfe8',
      curva: [25.5, 30.6, 35.6, 38.5, 42.0, 47.5, 39.6, 35.2, 33.8, 32.6, 31.8] },
    { id: 'k2so4sol', nome: 'K₂SO₄',              M: 174.26, cor: '#a78bfa', dot: '#ddd6fe',
      curva: [7.4, 9.3, 11.1, 13.0, 14.8, 16.5, 18.2, 19.8, 21.4, 22.7, 24.1] },
  ],

  SOLUBILIDADE: [
    { id: 'kno3',   nome: 'KNO₃',    cor: '#f59e0b', g: [13.3, 20.9, 31.6, 45.8, 63.9, 85.5, 110, 138, 169, 202, 246] },
    { id: 'nh4no3', nome: 'NH₄NO₃',  cor: '#fb923c', g: [118, 150, 192, 230, 297, 350, 410, 490, 576, 780, 1024] },
    { id: 'nh4cl',  nome: 'NH₄Cl',   cor: '#22d3ee', g: [29.4, 33.3, 37.2, 41.4, 45.8, 50.4, 55.2, 60.2, 65.6, 71.3, 77.3] },
    { id: 'nacl',   nome: 'NaCl',    cor: '#a3e635', g: [35.7, 35.8, 36.0, 36.3, 36.6, 37.0, 37.3, 37.8, 38.4, 39.0, 39.8] },
    { id: 'kclo3',  nome: 'KClO₃',   cor: '#f472b6', g: [3.3, 5.0, 7.4, 10.5, 14.0, 19.3, 24.5, 31.5, 38.5, 46.7, 56.2] },
    { id: 'na2so4', nome: 'Na₂SO₄',  cor: '#c084fc', g: [4.8, 9.1, 19.5, 40.8, 48.8, 46.7, 45.3, 44.3, 43.7, 42.9, 42.5] },
    { id: 'li2so4', nome: 'Li₂SO₄',  cor: '#94a3b8', g: [36.1, 35.5, 34.8, 34.2, 33.7, 33.1, 32.6, 32.1, 31.6, 31.0, 30.9] },
    { id: 'kcl',    nome: 'KCl',     cor: '#60a5fa', g: [27.6, 31.0, 34.0, 37.0, 40.0, 42.6, 45.5, 48.3, 51.1, 54.0, 56.7] },
    { id: 'kbr',    nome: 'KBr',     cor: '#2dd4bf', g: [53.5, 59.5, 65.2, 70.6, 75.5, 80.2, 85.5, 90.0, 95.0, 99.2, 104] },
    { id: 'ki',     nome: 'KI',      cor: '#fb7185', g: [128, 136, 144, 153, 162, 172, 182, 192, 202, 212, 222] },
    { id: 'nano3',  nome: 'NaNO₃',   cor: '#c026d3', g: [73, 80, 88, 96, 104, 114, 124, 135, 148, 162, 180] },
    { id: 'pbno32', nome: 'Pb(NO₃)₂', cor: '#eab308', g: [38, 46, 54, 63, 72, 80, 90, 100, 110, 121, 133] },
    { id: 'nh42so4', nome: '(NH₄)₂SO₄', cor: '#84cc16', g: [70.6, 73.0, 75.4, 78.0, 81.0, 84.5, 88.0, 92.0, 95.0, 98.0, 103] },
    { id: 'k2cr2o7', nome: 'K₂Cr₂O₇', cor: '#dc2626', g: [4.9, 7.4, 12.3, 18.1, 25.2, 33.2, 45.6, 59.8, 73.0, 87.1, 102] },
    { id: 'nabr',   nome: 'NaBr',    cor: '#0ea5e9', g: [79.5, 85, 88, 90, 92, 95, 99, 104, 108, 114, 121] },
    { id: 'naf',    nome: 'NaF',     cor: '#0891b2', g: [3.7, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0, 5.1, 5.2, 5.3, 5.4] },
    { id: 'licl',   nome: 'LiCl',    cor: '#facc15', g: [63.7, 67.2, 69.2, 74.5, 79.8, 85.2, 89.8, 91.3, 93.2, 95.5, 98.3] },
    { id: 'nai',    nome: 'NaI',     cor: '#818cf8', g: [159, 167, 175, 184, 191, 199, 207, 225, 275, 295, 302] },
    { id: 'agno3',  nome: 'AgNO₃',   cor: '#78716c', g: [122, 170, 216, 256, 300, 376, 440, 525, 585, 733, 952] },
    { id: 'k2co3',  nome: 'K₂CO₃',   cor: '#eab308', g: [105, 108, 111, 114, 117, 121, 126, 132, 138, 144, 151] },
    { id: 'bacl2',  nome: 'BaCl₂',   cor: '#f87171', g: [31.2, 33.3, 35.6, 37.8, 40.2, 42.9, 46.2, 49.4, 52.4, 55.8, 59.4] },
    { id: 'nh4br',  nome: 'NH₄Br',   cor: '#38bdf8', g: [60, 68, 76, 83, 91, 99, 108, 117, 126, 135, 145] },
    { id: 'cucl2',  nome: 'CuCl₂',   cor: '#22d3ee', g: [68.6, 70.9, 73.0, 74.5, 76.7, 79.2, 81.4, 84.4, 87.6, 91.2, 96.5] },
    { id: 'niso4',  nome: 'NiSO₄',   cor: '#84cc16', g: [26.6, 33.2, 38.4, 43.5, 47.9, 51.3, 34.5, 30.9, 30.0, 29.4, 28.9] },
    { id: 'mncl2',  nome: 'MnCl₂',   cor: '#fb7185', g: [63.4, 68.1, 73.9, 77.3, 80.6, 84.0, 87.8, 92.9, 98.1, 100.5, 102.7] },
    { id: 'cabr2',  nome: 'CaBr₂',   cor: '#fb923c', g: [125, 132, 137, 143, 150, 158, 168, 180, 195, 210, 230] },
    { id: 'srcl2',  nome: 'SrCl₂',   cor: '#fdba74', g: [43.5, 46.5, 50.5, 53.8, 59.7, 66.4, 77.0, 91.0, 96.5, 100.8, 104.9] },
    { id: 'cocl2',  nome: 'CoCl₂',   cor: '#60a5fa', g: [43.5, 47.7, 52.9, 66.8, 84.9, 90.5, 95.6, 97.9, 99.1, 100.9, 105.8] },
    { id: 'coso4',  nome: 'CoSO₄',   cor: '#f472b6', g: [25.5, 30.6, 35.6, 38.5, 42.0, 47.5, 39.6, 35.2, 33.8, 32.6, 31.8] },
    { id: 'k2so4sol', nome: 'K₂SO₄', cor: '#a78bfa', g: [7.4, 9.3, 11.1, 13.0, 14.8, 16.5, 18.2, 19.8, 21.4, 22.7, 24.1] },
  ],
  SOLUB_NOTA: 'NH₄NO₃ é o mais solúvel do grupo e dissolve endotermicamente (usado em compressas frias). Na₂SO₄ tem máximo perto de 32,4 °C; Li₂SO₄ é um dos raros sais cuja solubilidade DIMINUI com T. K₂Cr₂O₇ tem uma das curvas mais íngremes (ótimo pra recristalização purificadora). AgNO₃ é um dos sais mais solúveis e com a subida mais acentuada da tabela. NiSO₄, CoCl₂, CoSO₄ e SrCl₂ têm curvas com inflexão por causa de transições de hidrato — valores aproximados, simplificados pra fins didáticos. Na₂SO₄ e (NH₄)₂SO₄ foram conferidos contra a Wikipedia (fonte primária): valores batem com <0,3 g de diferença nos extremos 0 °C/100 °C. Valores ≈ de tabelas didáticas/CRC.',

  DIL: { corante: 'KMnO₄', corMax: '#7e22ce', cRef: 2.0 },

  LIQUIDOS: [
    { id: 'agua',    nome: 'Água',           te: 100,   cor: '#38bdf8', M: 18.02, rho: 1.00,
      antoine: { A: 8.07131, B: 1730.63, C: 233.426, tmin: 1,   tmax: 100 } },
    { id: 'etanol',  nome: 'Etanol',         te: 78.4,  cor: '#a78bfa', M: 46.07, rho: 0.789,
      antoine: { A: 8.2133,  B: 1652.05, C: 231.48,  tmin: -3,  tmax: 96 } },
    { id: 'metanol', nome: 'Metanol',        te: 64.7,  cor: '#4ade80', M: 32.04, rho: 0.792,
      antoine: { A: 8.0724,  B: 1574.99, C: 238.87,  tmin: -16, tmax: 91 } },
    { id: 'acetona', nome: 'Acetona',        te: 56.05, cor: '#facc15', M: 58.08, rho: 0.791,
      antoine: { A: 7.2316,  B: 1277.03, C: 237.23,  tmin: -32, tmax: 77 } },
    { id: 'eter',    nome: 'Éter etílico',   te: 34.6,  cor: '#f472b6', M: 74.12, rho: 0.713,
      pv: [[-74.3, 1], [-48.1, 10], [-27.7, 40], [-11.5, 100], [17.9, 400], [34.6, 760], [56.0, 1520], [90.0, 3800]] },
    { id: 'benzeno', nome: 'Benzeno',       te: 80.1,  cor: '#fb923c', M: 78.11, rho: 0.876,
      antoine: { A: 6.90565, B: 1211.033, C: 220.790, tmin: 8,   tmax: 103 } },
    { id: 'tolueno', nome: 'Tolueno',       te: 110.6, cor: '#2dd4bf', M: 92.14, rho: 0.867,
      antoine: { A: 6.95464, B: 1344.800, C: 219.482, tmin: 6,   tmax: 137 } },
    { id: 'hexano',  nome: 'Hexano',        te: 68.7,  cor: '#cbd5e1', M: 86.18, rho: 0.655,
      antoine: { A: 6.87776, B: 1171.530, C: 224.366, tmin: -25, tmax: 92 } },
    { id: 'clorof',  nome: 'Clorofórmio',   te: 61.2,  cor: '#818cf8', M: 119.38, rho: 1.489,
      antoine: { A: 6.90328, B: 1163.03,  C: 227.4,   tmin: -10, tmax: 60 } },
    { id: 'isoprop', nome: 'Isopropanol',   te: 82.3,  cor: '#fb7185', M: 60.10, rho: 0.786,
      antoine: { A: 8.87829, B: 2010.32,  C: 252.636, tmin: 8,   tmax: 100 } },
    { id: 'pentano', nome: 'Pentano',       te: 36.1,  cor: '#fde047', M: 72.15, rho: 0.626,
      antoine: { A: 6.85296, B: 1064.63,  C: 232.0,   tmin: -50, tmax: 58 } },
    { id: 'heptano', nome: 'Heptano',       te: 98.4,  cor: '#a3e635', M: 100.20, rho: 0.684,
      antoine: { A: 6.89386, B: 1264.37,  C: 216.64,  tmin: -2,  tmax: 124 } },
    { id: 'octano',  nome: 'Octano',        te: 125.6, cor: '#65a30d', M: 114.23, rho: 0.703,
      antoine: { A: 6.91868, B: 1351.99,  C: 209.15,  tmin: 26,  tmax: 152 } },
    { id: 'propanol', nome: '1-Propanol',   te: 97.2,  cor: '#c084fc', M: 60.10, rho: 0.803,
      antoine: { A: 8.37895, B: 1788.02,  C: 227.438, tmin: -15, tmax: 105 } },
    { id: 'butanol', nome: '1-Butanol',     te: 117.7, cor: '#e879f9', M: 74.12, rho: 0.810,
      antoine: { A: 7.83800, B: 1558.19,  C: 196.881, tmin: 15,  tmax: 131 } },
    { id: 'cs2',     nome: 'Dissulfeto de carbono', te: 46.3, cor: '#fbbf24', M: 76.14, rho: 1.263,
      antoine: { A: 6.84224, B: 1169.11,  C: 241.59,  tmin: -30, tmax: 80 } },
    { id: 'diclorom', nome: 'Diclorometano', te: 39.6, cor: '#67e8f9', M: 84.93, rho: 1.326,
      antoine: { A: 7.40916, B: 1325.93,  C: 252.60,  tmin: -37, tmax: 60 } },
    { id: 'acetatoetila', nome: 'Acetato de etila', te: 77.1, cor: '#fda4af', M: 88.11, rho: 0.902,
      antoine: { A: 7.10179, B: 1244.95,  C: 217.88,  tmin: -20, tmax: 76 } },
    { id: 'thf',     nome: 'Tetra-hidrofurano (THF)', te: 66.0, cor: '#5eead4', M: 72.11, rho: 0.889,
      antoine: { A: 6.99515, B: 1202.29,  C: 226.25,  tmin: -20, tmax: 90 } },
  ],

  KE: 0.52,
  KC: 1.86,
  R:  0.082,
  MOL_AGUA_KG: 55.5,

  /* ── Solutos do modo Ebulioscopia/Crioscopia — agora com massa molar
        REAL (M), usada para comparar a "massa molar aparente" (se alguém
        ignorasse a dissociação) com a massa molar verdadeira. ── */
  SOLUTOS_COL: [
    { id: 'glicose', nome: 'Glicose C₆H₁₂O₆', i: 1, M: 180.16, dot: '#fbbf24', tipo: 'molecular (não ioniza)' },
    { id: 'sacarcol', nome: 'Sacarose C₁₂H₂₂O₁₁', i: 1, M: 342.30, dot: '#fde68a', tipo: 'molecular (não ioniza)' },
    { id: 'ureia',   nome: 'Ureia CO(NH₂)₂',   i: 1, M: 60.06,  dot: '#93c5fd', tipo: 'molecular (não ioniza)' },
    { id: 'metanolc', nome: 'Metanol',         i: 1, M: 32.04,  dot: '#86efac', tipo: 'molecular (não ioniza)' },
    { id: 'etanolc', nome: 'Etanol',           i: 1, M: 46.07,  dot: '#c4b5fd', tipo: 'molecular (não ioniza)' },
    { id: 'etilenoglicol', nome: 'Etilenoglicol', i: 1, M: 62.07, dot: '#7dd3fc', tipo: 'molecular (não ioniza)' },
    { id: 'glicerina', nome: 'Glicerina C₃H₈O₃', i: 1, M: 92.09, dot: '#fed7aa', tipo: 'molecular (não ioniza)' },
    { id: 'frutose', nome: 'Frutose C₆H₁₂O₆', i: 1, M: 180.16, dot: '#fca5a5', tipo: 'molecular (não ioniza)' },
    { id: 'maltose', nome: 'Maltose C₁₂H₂₂O₁₁', i: 1, M: 342.30, dot: '#fef08a', tipo: 'molecular (não ioniza)' },
    { id: 'lactose', nome: 'Lactose C₁₂H₂₂O₁₁', i: 1, M: 342.30, dot: '#e9d5ff', tipo: 'molecular (não ioniza)' },
    { id: 'manitol', nome: 'Manitol C₆H₁₄O₆', i: 1, M: 182.17, dot: '#a7f3d0', tipo: 'molecular (não ioniza)' },
    { id: 'sorbitol', nome: 'Sorbitol C₆H₁₄O₆', i: 1, M: 182.17, dot: '#99f6e4', tipo: 'molecular (não ioniza)' },
    { id: 'acetonac', nome: 'Acetona',         i: 1, M: 58.08,  dot: '#fde047', tipo: 'molecular (não ioniza)' },
    { id: 'isopropc', nome: 'Isopropanol',     i: 1, M: 60.10,  dot: '#f9a8d4', tipo: 'molecular (não ioniza)' },
    { id: 'acidoborico', nome: 'Ácido bórico H₃BO₃', i: 1, M: 61.83, dot: '#e2e8f0', tipo: 'molecular (ácido fraco, quase não ioniza)' },
    { id: 'nacl',    nome: 'NaCl',            i: 2, M: 58.44,  dot: '#e2e8f0', tipo: 'iônico → Na⁺ + Cl⁻' },
    { id: 'kclcol',  nome: 'KCl',             i: 2, M: 74.55,  dot: '#fecaca', tipo: 'iônico → K⁺ + Cl⁻' },
    { id: 'nabrcol', nome: 'NaBr',            i: 2, M: 102.89, dot: '#bae6fd', tipo: 'iônico → Na⁺ + Br⁻' },
    { id: 'naicol',  nome: 'NaI',             i: 2, M: 149.89, dot: '#c7d2fe', tipo: 'iônico → Na⁺ + I⁻' },
    { id: 'nafcol',  nome: 'NaF',             i: 2, M: 41.99,  dot: '#a5f3fc', tipo: 'iônico → Na⁺ + F⁻' },
    { id: 'lici',    nome: 'LiCl',            i: 2, M: 42.39,  dot: '#fde68a', tipo: 'iônico → Li⁺ + Cl⁻' },
    { id: 'kicol',   nome: 'KI',              i: 2, M: 166.00, dot: '#fecdd3', tipo: 'iônico → K⁺ + I⁻' },
    { id: 'kbrcol',  nome: 'KBr',             i: 2, M: 119.00, dot: '#99f6e4', tipo: 'iônico → K⁺ + Br⁻' },
    { id: 'nh4clcol', nome: 'NH₄Cl',          i: 2, M: 53.49,  dot: '#a5f3fc', tipo: 'iônico → NH₄⁺ + Cl⁻' },
    { id: 'agno3',   nome: 'AgNO₃',           i: 2, M: 169.87, dot: '#e5e7eb', tipo: 'iônico → Ag⁺ + NO₃⁻' },
    { id: 'nano3col', nome: 'NaNO₃',          i: 2, M: 85.00,  dot: '#f5d0fe', tipo: 'iônico → Na⁺ + NO₃⁻' },
    { id: 'kno3col', nome: 'KNO₃',            i: 2, M: 101.10, dot: '#f1f5f9', tipo: 'iônico → K⁺ + NO₃⁻' },
    { id: 'cuso4col', nome: 'CuSO₄',          i: 2, M: 159.61, dot: '#3b82f6', tipo: 'iônico → Cu²⁺ + SO₄²⁻' },
    { id: 'mgso4col', nome: 'MgSO₄',          i: 2, M: 120.37, dot: '#bbf7d0', tipo: 'iônico → Mg²⁺ + SO₄²⁻' },
    { id: 'znso4col', nome: 'ZnSO₄',          i: 2, M: 161.47, dot: '#d9f99d', tipo: 'iônico → Zn²⁺ + SO₄²⁻' },
    { id: 'cacl2',   nome: 'CaCl₂',           i: 3, M: 110.98, dot: '#86efac', tipo: 'iônico → Ca²⁺ + 2 Cl⁻' },
    { id: 'mgcl2',   nome: 'MgCl₂',           i: 3, M: 95.21,  dot: '#bbf7d0', tipo: 'iônico → Mg²⁺ + 2 Cl⁻' },
    { id: 'k2so4',   nome: 'K₂SO₄',           i: 3, M: 174.26, dot: '#ddd6fe', tipo: 'iônico → 2 K⁺ + SO₄²⁻' },
    { id: 'na2so4col', nome: 'Na₂SO₄',        i: 3, M: 142.04, dot: '#e9d5ff', tipo: 'iônico → 2 Na⁺ + SO₄²⁻' },
    { id: 'na2co3col', nome: 'Na₂CO₃',        i: 3, M: 105.99, dot: '#fef08a', tipo: 'iônico → 2 Na⁺ + CO₃²⁻' },
    { id: 'k2co3col', nome: 'K₂CO₃',          i: 3, M: 138.21, dot: '#fde68a', tipo: 'iônico → 2 K⁺ + CO₃²⁻' },
    { id: 'bacl2',   nome: 'BaCl₂',           i: 3, M: 208.23, dot: '#fca5a5', tipo: 'iônico → Ba²⁺ + 2 Cl⁻' },
    { id: 'srcl2',   nome: 'SrCl₂',           i: 3, M: 158.53, dot: '#fdba74', tipo: 'iônico → Sr²⁺ + 2 Cl⁻' },
    { id: 'nh42so4col', nome: '(NH₄)₂SO₄',   i: 3, M: 132.14, dot: '#d9f99d', tipo: 'iônico → 2 NH₄⁺ + SO₄²⁻' },
    { id: 'na2s',    nome: 'Na₂S',            i: 3, M: 78.04,  dot: '#fef9c3', tipo: 'iônico → 2 Na⁺ + S²⁻' },
    { id: 'cabr2',   nome: 'CaBr₂',           i: 3, M: 199.89, dot: '#fecaca', tipo: 'iônico → Ca²⁺ + 2 Br⁻' },
    { id: 'cano32',  nome: 'Ca(NO₃)₂',        i: 3, M: 164.09, dot: '#fef08a', tipo: 'iônico → Ca²⁺ + 2 NO₃⁻' },
    { id: 'alcl3',   nome: 'AlCl₃',           i: 4, M: 133.34, dot: '#fed7aa', tipo: 'iônico → Al³⁺ + 3 Cl⁻' },
    { id: 'fecl3',   nome: 'FeCl₃',           i: 4, M: 162.20, dot: '#fdba74', tipo: 'iônico → Fe³⁺ + 3 Cl⁻' },
    { id: 'alno33',  nome: 'Al(NO₃)₃',        i: 4, M: 213.00, dot: '#fde68a', tipo: 'iônico → Al³⁺ + 3 NO₃⁻' },
    { id: 'na3po4',  nome: 'Na₃PO₄',          i: 4, M: 163.94, dot: '#e0f2fe', tipo: 'iônico → 3 Na⁺ + PO₄³⁻' },
    { id: 'k3po4',   nome: 'K₃PO₄',           i: 4, M: 212.27, dot: '#fce7f3', tipo: 'iônico → 3 K⁺ + PO₄³⁻' },
    { id: 'al2so43', nome: 'Al₂(SO₄)₃',       i: 5, M: 342.15, dot: '#e9d5ff', tipo: 'iônico → 2 Al³⁺ + 3 SO₄²⁻' },
    { id: 'fe2so43', nome: 'Fe₂(SO₄)₃',       i: 5, M: 399.88, dot: '#fecaca', tipo: 'iônico → 2 Fe³⁺ + 3 SO₄²⁻' },
    { id: 'cocl2',   nome: 'CoCl₂',           i: 3, M: 129.84, dot: '#93c5fd', tipo: 'iônico → Co²⁺ + 2 Cl⁻' },
    { id: 'niso4',   nome: 'NiSO₄',           i: 2, M: 154.75, dot: '#bef264', tipo: 'iônico → Ni²⁺ + SO₄²⁻' },
    { id: 'mncl2',   nome: 'MnCl₂',           i: 3, M: 125.84, dot: '#fda4af', tipo: 'iônico → Mn²⁺ + 2 Cl⁻' },
  ],

  /* ── Solventes para ebulioscopia/crioscopia — Ke/Kc REAIS de cada
        solvente (não só água). FONTES: Ke/Kc do benzeno, ácido acético e
        cânfora — valores consagrados na literatura (Atkins; Wikipedia
        "Ebullioscopic/Cryoscopic constant", que cita a mesma origem
        termodinâmica Kb=RTb²M/ΔHvap, Kf=RMTf²/ΔHfus). A cânfora tem o
        MAIOR Kc conhecido (37,7 °C·kg/mol) — por isso é o solvente
        clássico do método de Rast para determinar massa molar: mesmo
        pouquíssimo soluto já desloca bastante o ponto de fusão. molKg =
        mol de solvente puro por kg (1000/massa molar do solvente),
        usado na fração molar da tonoscopia. ── */
  SOLVENTES_COLIG: [
    { id: 'agua',    nome: 'Água',          Te: 100,   Tc: 0,   Ke: 0.52, Kc: 1.86, molKg: 55.5, cor: '#38bdf8' },
    { id: 'benzeno', nome: 'Benzeno',       Te: 80.1,  Tc: 5.5, Ke: 2.53, Kc: 5.12, molKg: 12.8, cor: '#facc15' },
    { id: 'acetico', nome: 'Ácido acético', Te: 118.1, Tc: 16.6, Ke: 3.08, Kc: 3.90, molKg: 16.6, cor: '#fca5a5' },
    { id: 'canfora', nome: 'Cânfora',       Te: 204,   Tc: 176, Ke: 5.95, Kc: 37.7, molKg: 6.6,  cor: '#d8b4fe' },
    { id: 'ccl4',    nome: 'Tetracloreto de carbono', Te: 76.7, Tc: -22.9, Ke: 5.03, Kc: 30.0, molKg: 6.5, cor: '#94a3b8' },
    { id: 'ciclohex', nome: 'Ciclohexano',  Te: 80.7,  Tc: 6.5, Ke: 2.79, Kc: 20.2, molKg: 11.9, cor: '#22d3ee' },
    { id: 'dioxano', nome: '1,4-Dioxano',   Te: 101.3, Tc: 11.8, Ke: 3.01, Kc: 4.63, molKg: 11.3, cor: '#a3e635' },
    { id: 'nitrobenzeno', nome: 'Nitrobenzeno', Te: 210.9, Tc: 5.7, Ke: 5.24, Kc: 6.90, molKg: 8.1, cor: '#fb923c' },
    { id: 'anilina', nome: 'Anilina',       Te: 184.1, Tc: -6.0, Ke: 3.69, Kc: 5.87, molKg: 10.7, cor: '#e879f9' },
    { id: 'formico', nome: 'Ácido fórmico', Te: 100.8, Tc: 8.4, Ke: 2.40, Kc: 2.77, molKg: 21.7, cor: '#f87171' },
  ],

  GASES_HENRY: [
    { id: 'co2', nome: 'CO₂ (gás carbônico)', kH25: 0.034,   decaiK: 0.0165, cor: '#94a3b8', ctx: 'refrigerante e água com gás' },
    { id: 'o2',  nome: 'O₂ (oxigênio)',       kH25: 0.0013,  decaiK: 0.0121, cor: '#38bdf8', ctx: 'oxigênio dissolvido em rios e aquários' },
    { id: 'n2',  nome: 'N₂ (nitrogênio)',     kH25: 0.00061, decaiK: 0.0121, cor: '#a78bfa', ctx: 'nitrogênio do ar dissolvido na água' },
    { id: 'ar',  nome: 'Ar (argônio)',        kH25: 0.0014,  decaiK: 0.0121, cor: '#fbbf24', ctx: 'gás nobre, ~1% do ar atmosférico' },
    { id: 'ch4', nome: 'CH₄ (metano)',        kH25: 0.0014,  decaiK: 0.0130, cor: '#4ade80', ctx: 'gás natural dissolvido em água subterrânea' },
    { id: 'h2',  nome: 'H₂ (hidrogênio)',     kH25: 0.00078, decaiK: 0.0121, cor: '#f472b6', ctx: 'o gás mais leve, baixíssima solubilidade' },
    { id: 'he',  nome: 'He (hélio)',          kH25: 0.00038, decaiK: 0.0090, cor: '#fde047', ctx: 'gás inerte usado em balões e mergulho profundo' },
    { id: 'ne',  nome: 'Ne (neônio)',         kH25: 0.00045, decaiK: 0.0100, cor: '#fca5a5', ctx: 'gás nobre usado em placas luminosas' },
    { id: 'kr',  nome: 'Kr (criptônio)',      kH25: 0.0024,  decaiK: 0.0125, cor: '#5eead4', ctx: 'gás nobre mais pesado, mais solúvel que os leves' },
    { id: 'xe',  nome: 'Xe (xenônio)',        kH25: 0.0043,  decaiK: 0.0130, cor: '#818cf8', ctx: 'gás nobre mais pesado da série, o mais solúvel deles' },
    { id: 'co',  nome: 'CO (monóxido de carbono)', kH25: 0.0010, decaiK: 0.0121, cor: '#78716c', ctx: 'gás tóxico, solubilidade parecida com N₂/O₂' },
    { id: 'c2h6', nome: 'C₂H₆ (etano)',       kH25: 0.0019,  decaiK: 0.0140, cor: '#a3e635', ctx: 'componente do gás natural' },
    { id: 'c2h4', nome: 'C₂H₄ (eteno/etileno)', kH25: 0.0047, decaiK: 0.0140, cor: '#86efac', ctx: 'hormônio vegetal e matéria-prima petroquímica' },
    { id: 'c2h2', nome: 'C₂H₂ (acetileno)',   kH25: 0.041,   decaiK: 0.0150, cor: '#fdba74', ctx: 'gás usado em maçaricos de solda' },
    { id: 'sf6',  nome: 'SF₆ (hexafluoreto de enxofre)', kH25: 0.00024, decaiK: 0.0110, cor: '#e2e8f0', ctx: 'gás isolante elétrico, potente gás de efeito estufa' },
    { id: 'no',  nome: 'NO (óxido nítrico)',  kH25: 0.0019,  decaiK: 0.0130, cor: '#f87171', ctx: 'radical sinalizador no corpo, poluente atmosférico' },
  ],

  /* ── Desafios do "Desafio da Destilação" (minigame) — cada um começa
        com uma mistura definida e um objetivo: purificar o líquido A
        destilando repetidamente. O Desafio 1 é o caso real (etanol+água)
        que trava no azeótropo; o Desafio 2 é um par sem desvio forte, só
        pra contrastar: sem azeótropo, a destilação repetida CONSEGUE
        chegar perto de 100% de pureza. ── */
  DESAFIOS_DESTILACAO: [
    { id: 'etanol-agua', nome: 'Desafio 1: Purifique o Etanol', aId: 'etanol', bId: 'agua', desvio: 'positivo', xA0: 0.12, T: 78,
      contexto: 'Mistura fermentada típica (~12% de etanol) — tente destilar até a pureza máxima.' },
    { id: 'metanol-etanol', nome: 'Desafio 2: Purifique o Metanol (sem azeótropo)', aId: 'metanol', bId: 'etanol', desvio: 'ideal', xA0: 0.15, T: 68,
      contexto: 'Par praticamente ideal — sem azeótropo, dá pra chegar bem perto de 100% de pureza.' },
    { id: 'benzeno-tolueno', nome: 'Desafio 3: Purifique o Benzeno (par ideal clássico)', aId: 'benzeno', bId: 'tolueno', desvio: 'ideal', xA0: 0.25, T: 95,
      contexto: 'Benzeno+tolueno é O exemplo clássico de solução ideal em livros-texto — moléculas parecidas, sem azeótropo, purificação total possível.' },
    { id: 'clorof-acetona', nome: 'Desafio 4: Purifique a Acetona (desvio negativo real)', aId: 'acetona', bId: 'clorof', desvio: 'negativo', xA0: 0.7, T: 55,
      contexto: 'Clorofórmio+acetona formam pontes de hidrogênio entre si — desvio negativo bem documentado, com azeótropo de ebulição MÁXIMA.' },
    { id: 'isoprop-agua', nome: 'Desafio 5: Purifique o Isopropanol', aId: 'isoprop', bId: 'agua', desvio: 'positivo', xA0: 0.20, T: 80,
      contexto: 'Isopropanol+água formam um azeótropo real perto de 91% de álcool — por isso o "álcool isopropílico 99%" já é quase o limite prático.' },
    { id: 'etanol-acetatoetila', nome: 'Desafio 6: Purifique o Acetato de Etila', aId: 'acetatoetila', bId: 'etanol', desvio: 'positivo', xA0: 0.30, T: 72,
      contexto: 'Etanol+acetato de etila (o solvente do removedor de esmalte) formam um azeótropo real — clássico na indústria de solventes.' },
    { id: 'thf-agua', nome: 'Desafio 7: Purifique o THF', aId: 'thf', bId: 'agua', desvio: 'positivo', xA0: 0.35, T: 64,
      contexto: 'Tetra-hidrofurano+água formam azeótropo real — por isso o THF de laboratório vem quase sempre anidro, vendido já seco.' },
    { id: 'pentano-hexano', nome: 'Desafio 8: Separe Pentano de Hexano (quase ideal)', aId: 'pentano', bId: 'hexano', desvio: 'ideal', xA0: 0.4, T: 45,
      contexto: 'Dois alcanos muito parecidos — comportamento praticamente ideal, sem azeótropo, como benzeno+tolueno.' },
    { id: 'propanol-agua', nome: 'Desafio 9: Purifique o 1-Propanol', aId: 'propanol', bId: 'agua', desvio: 'positivo', xA0: 0.15, T: 88,
      contexto: 'Álcoois maiores também formam azeótropos reais com água — o padrão se repete em toda a família dos alcoóis.' },
    { id: 'diclorom-hexano', nome: 'Desafio 10: Separe Diclorometano de Hexano', aId: 'diclorom', bId: 'hexano', desvio: 'positivo', xA0: 0.5, T: 50,
      contexto: 'Um clorado e um alcano — moléculas bem diferentes entre si, desvio positivo esperado da diferença de polaridade.' },
  ],

  MECH_B: ['pvap', 'colig', 'osmose', 'henry', 'raoult'],

  MODES: [
    {
      id: 'classificacao', icon: '🔦', sigla: 'sol · colóide · susp.', nome: 'Classificação de Misturas', sub: 'Tamanho de partícula e efeito Tyndall',
      hint: 'Escolha uma mistura do dia a dia, observe o feixe de luz atravessando o béquer e decida: é uma solução verdadeira, um colóide ou uma suspensão?',
      info: 'Misturas se classificam pelo tamanho das partículas dispersas. Numa solução verdadeira (partículas menores que 1 nm) o feixe de luz atravessa sem se espalhar. Num colóide (1–1000 nm) o feixe se torna visível — o efeito Tyndall — mas as partículas não sedimentam com o tempo. Numa suspensão (maiores que 1000 nm) as partículas são grandes o bastante para sedimentar e podem ser retidas por filtração comum.',
      formula: 'solução < 1 nm   ·   colóide 1–1000 nm   ·   suspensão > 1000 nm',
      formulaNote: 'O efeito Tyndall (espalhamento de luz) distingue colóides de soluções verdadeiras; a sedimentação com o tempo distingue suspensões de colóides.',
      hintCanvas: '',
      overlay: 'Classificação de misturas', panels: ['panel-classificacao'], primary: 'dica-mix',
    },
    {
      id: 'preparo', icon: '🧂', sigla: 'C = m/V', nome: 'Preparo de Solução', sub: 'Concentração, temperatura e saturação',
      hint: 'Escolha um soluto, ajuste massa, volume de água e temperatura, e dissolva; se passar do limite de solubilidade NESSA temperatura, sobra corpo de fundo. Antes de dissolver, os resultados ficam zerados — é um experimento, não uma resposta pronta.',
      info: 'Prepare uma solução real: a concentração comum é C = m/V e a molaridade é M = C/MM. O limite de solubilidade de cada soluto muda com a temperatura (curva real, igual ao modo "Curvas") — o que passa do limite não dissolve e fica como corpo de fundo. A "concentração medida" inclui uma pequena margem de erro experimental, como aconteceria com vidraria real de laboratório.',
      formula: 'C = m₁/V   ·   M = m₁/(MM·V)',
      formulaNote: 'm₁ = massa do soluto (g) · V = volume da solução (L) · MM = massa molar (g/mol). Limite: solubilidade na temperatura escolhida (g/100 g de água), variável por soluto.',
      hintCanvas: 'Enter/Espaço dissolve o soluto',
      overlay: 'Preparo', panels: ['panel-preparo'], primary: 'dissolver',
    },
    {
      id: 'diluicao', icon: '💧', sigla: 'C₁V₁ = C₂V₂', nome: 'Diluição e Mistura', sub: 'KMnO₄ por torneiras',
      hint: 'Abra as torneiras para transferir a(s) solução(ões) — e, na diluição, também água — para um béquer maior, e veja a cor acompanhar a nova concentração.',
      info: 'Na diluição, a massa de soluto não muda: C₁V₁ = C₂V₂ — as torneiras despejam a solução concentrada e a água num béquer maior, e a cor do KMnO₄ enfraquece. Na mistura de soluções do MESMO soluto, duas torneiras despejam A e B no mesmo béquer maior, e a concentração final é a média ponderada pelos volumes.',
      formula: 'C₁V₁ = C₂V₂   ·   C_f = (C₁V₁ + C₂V₂)/(V₁ + V₂)',
      formulaNote: 'Válido porque a massa de soluto se conserva (diluição) ou se soma (mistura).',
      hintCanvas: 'Enter/Espaço abre as torneiras',
      overlay: 'Diluição · KMnO₄', panels: ['panel-diluicao'], primary: 'aplicar',
    },
    {
      id: 'curvas', icon: '📈', sigla: 'g/100 g', nome: 'Curvas de Solubilidade', sub: 'Quinze sais × temperatura',
      hint: 'Compare curvas reais de solubilidade, mova a temperatura e a massa, ANALISE o gráfico e responda: a solução está insaturada, saturada ou tem corpo de fundo?',
      info: 'A curva de solubilidade mostra quantos gramas de sal saturam 100 g de água em cada temperatura. Abaixo da curva a solução é insaturada; sobre a curva, saturada; acima, o excesso vira corpo de fundo (resfriar lentamente uma saturada quente pode gerar solução supersaturada, instável). Em vez de o simulador classificar por você, você analisa o gráfico e escolhe a resposta — e o placar registra seus acertos.',
      formula: 'coef. de solubilidade = g de soluto / 100 g de H₂O',
      formulaNote: 'KNO₃, NH₄NO₃ e NH₄Cl: dissolução endotérmica (sobem com T). Li₂SO₄ desce. Na₂SO₄ tem pico em ≈32,4 °C.',
      hintCanvas: 'Enter/Espaço dá uma dica — as respostas ficam nos botões da barra lateral',
      overlay: 'Curvas de solubilidade', panels: ['panel-curvas'], primary: 'dica',
    },
    {
      id: 'pvap', icon: '♨️', sigla: 'P_v × T', nome: 'Pressão de Vapor', sub: 'Ebulição e altitude',
      hint: 'Aqueça dez líquidos, compare suas curvas de pressão de vapor (equação de Antoine) e veja a fervura chegar quando a pressão de vapor iguala a atmosférica.',
      info: 'Um líquido ferve quando sua pressão de vapor iguala a pressão externa. Aqui a curva de cada líquido vem da equação de Antoine, log₁₀(P) = A − B/(C+T), ajustada a dados reais — por isso a curva é contínua e você pode extrapolar com confiança. Líquidos mais voláteis (éter, acetona) alcançam 760 mmHg com bem menos temperatura que a água. Reduzindo a pressão externa — como na altitude — a água ferve abaixo de 100 °C.',
      formula: 'log₁₀(P_mmHg) = A − B/(C + T)',
      formulaNote: 'Coeficientes de Antoine (A, B, C) por líquido — NIST WebBook / Yaws. Ao nível do mar P_ext = 760 mmHg. Em La Paz (~4.000 m), P_ext ≈ 470 mmHg e a água ferve perto de 87 °C.',
      hintCanvas: 'Enter/Espaço anuncia o estado do líquido',
      overlay: 'Pressão de vapor', panels: ['panel-pvap'], primary: 'pv-status',
    },
    {
      id: 'raoult', icon: '⚗️', sigla: 'P = xₐP°ₐ+x_bP°_b', nome: 'Misturas de Líquidos Voláteis', sub: 'Por que nem toda mistura se comporta "como devia"',
      hint: 'Comece pelo botão "Exemplo real: Etanol + Água" — é um caso bem documentado. Depois explore livremente: 1) escolha os líquidos, 2) escolha como A e B interagem, 3) mova a composição e compare a reta pontilhada (previsão) com a curva sólida (realidade).',
      info: 'Quando dois líquidos voláteis se misturam, cada um evapora um pouco, e a soma das duas pressões de vapor dá a pressão total. Se as moléculas de A e B interagem entre si do MESMO jeito que interagem consigo mesmas, essa soma é uma simples reta (Lei de Raoult) — é o caso "ideal". Na prática, a maioria das misturas não é assim: se as moléculas A–B se atraem MENOS do que A–A e B–B, elas "preferem" escapar para o vapor, e a pressão real fica ACIMA da reta — desvio positivo (caso real e bem documentado: etanol+água, que forma um azeótropo a ≈89,5% em fração molar de etanol, fervendo a 78,2 °C — use o botão de exemplo real para conferir que o modelo simplificado chega perto desse valor). Se A–B se atraem MAIS, o oposto acontece e a pressão fica ABAIXO da reta — desvio negativo. Quando o desvio é forte o bastante, a curva real forma um pico (ou vale) que a reta ideal não tem: esse ponto é o azeótropo — ali o vapor tem a MESMA composição do líquido, então destilar não separa mais nada, por mais que se repita o processo.',
      formula: 'P_ideal = xₐP°ₐ + x_bP°_b   ·   P_real = xₐγₐP°ₐ + x_bγ_bP°_b',
      formulaNote: 'γ = coeficiente de atividade (modelo de Margules simplificado, só para ilustrar a FORMA do desvio — os valores exatos de azeótropos reais variam por sistema, com exceção de etanol+água, calibrado contra o dado real). Ideal: γ=1, a curva real coincide com a reta.',
      hintCanvas: 'Enter/Espaço anuncia o estado da mistura',
      overlay: 'Misturas voláteis', panels: ['panel-raoult'], primary: 'raoult-status',
    },
    {
      id: 'colig', icon: '🧊', sigla: 'ΔT = K·W·i', nome: 'Ebulioscopia e Crioscopia', sub: 'Determinação de massa molar',
      hint: 'Escolha o solvente e o soluto, ajuste a molalidade e compare a massa molar REAL do soluto com a massa molar "aparente" que alguém calcularia se ignorasse a dissociação — um erro clássico de laboratório.',
      info: 'Soluto não volátil abaixa a pressão de vapor do solvente (tonoscopia, Lei de Raoult). Consequência: a solução ferve ACIMA do ponto de ebulição do solvente puro (ΔTe = Ke·W·i) e congela ABAIXO do ponto de congelamento (ΔTc = Kc·W·i). Isso é a base real dos métodos de ebulioscopia e crioscopia para descobrir a massa molar de um soluto desconhecido: mede-se ΔT e, SE a pessoa esquecer de considerar o fator i (dissociação), a massa molar calculada sai errada — para eletrólitos, sai i vezes menor que a real. A cânfora tem o maior Kc conhecido (37,7 °C·kg/mol) e por isso é o solvente clássico do método de Rast: mesmo pouquíssimo soluto já desloca bastante o ponto de fusão, tornando a medida mais precisa.',
      formula: 'ΔTe = Ke·W·i   ·   ΔTc = Kc·W·i   ·   M_aparente = M_real / i',
      formulaNote: 'Ke/Kc dependem do SOLVENTE, não do soluto (água: 0,52/1,86 · benzeno: 2,53/5,12 · ácido acético: 3,08/3,90 · cânfora: 5,95/37,7 · CCl₄: 5,03/30,0 · ciclohexano: 2,79/20,2 °C·kg·mol⁻¹). W = molalidade (mol de soluto/kg de solvente).',
      hintCanvas: 'Enter/Espaço anuncia os novos pontos',
      overlay: 'Efeitos coligativos', panels: ['panel-colig'], primary: 'colig-status',
    },
    {
      id: 'osmose', icon: '🫧', sigla: 'π = MRT', nome: 'Osmose', sub: 'Membrana e osmose reversa',
      hint: 'Duas soluções separadas por membrana semipermeável: a água atravessa para o lado mais concentrado até as concentrações se igualarem — ou aplique pressão para inverter o fluxo (osmose reversa).',
      info: 'Na osmose só o SOLVENTE atravessa a membrana, do meio menos concentrado (hipotônico) para o mais concentrado (hipertônico). Aqui o fluxo é simulado de verdade: a água muda de lado a uma taxa proporcional à diferença de concentração e, como o soluto fica retido, a concentração de quem perde água sobe e a de quem ganha desce — até as duas se igualarem e o nível parar, exatamente como um osmômetro fechado. A pressão osmótica é π = M·R·T — por isso soro fisiológico precisa ser isotônico ao sangue. Aplicando uma pressão MAIOR que π no lado concentrado, o fluxo se inverte: é a osmose reversa, usada na dessalinização de água do mar — água pura atravessa a membrana e os sais ficam retidos.',
      formula: 'π = M·R·T   ·   osmose reversa: P_aplicada > Δπ',
      formulaNote: 'M em mol/L, R = 0,082 atm·L·mol⁻¹·K⁻¹, T em kelvin. Fluxo de água simulado por conservação de massa: dV/dt ∝ (Δπ efetivo − pressão aplicada), convertida para a mesma unidade via π=MRT.',
      hintCanvas: 'Enter/Espaço inicia o fluxo osmótico',
      overlay: 'Osmose', panels: ['panel-osmose'], primary: 'osmose-run',
    },
    {
      id: 'henry', icon: '🥤', sigla: 'C = kH·P', nome: 'Lei de Henry', sub: 'Gases dissolvidos em água',
      hint: 'Escolha um gás, ajuste pressão e temperatura, e abra a garrafa para ver o excesso escapar em bolhas — como um refrigerante.',
      info: 'A Lei de Henry diz que a concentração de um gás dissolvido é proporcional à sua pressão parcial: C = kH·P. É por isso que o refrigerante é engarrafado sob pressão de CO₂ — ao abrir, a pressão cai para 1 atm e o gás em excesso escapa em bolhas até a nova concentração de equilíbrio. A solubilidade de gases também CAI com a temperatura (o oposto dos sólidos): água quente retém menos gás — por isso peixes sofrem em água quente e o refrigerante quente perde o gás mais rápido.',
      formula: 'C = kH(T) · P',
      formulaNote: 'kH em mol·L⁻¹·atm⁻¹, a 25 °C: O₂ 1,3×10⁻³ · N₂ 6,1×10⁻⁴ · CO₂ 3,4×10⁻² · Ar 1,4×10⁻³ · CH₄ 1,4×10⁻³ · H₂ 7,8×10⁻⁴ (Sander 2015). kH cai exponencialmente com T.',
      hintCanvas: 'Enter/Espaço abre ou fecha a garrafa',
      overlay: 'Lei de Henry', panels: ['panel-henry'], primary: 'henry-abrir',
    },
  ],

  CURIOSIDADES: [
    'O soro fisiológico é uma solução 0,9% de NaCl — cerca de 9 g de sal por litro, a mesma salinidade do plasma sanguíneo.',
    'A água do mar tem em média 35 g de sais por litro; por isso beber água do mar desidrata: o corpo gasta mais água para eliminar o sal.',
    'Refrigerante é uma solução supersaturada de CO₂ sob pressão — ao abrir a garrafa, a pressão cai e o excesso de gás escapa em bolhas.',
    'Compressas instantâneas usam a dissolução ENDOTÉRMICA do NH₄NO₃: ao dissolver, a bolsa esfria de verdade.',
    'O açúcar é muito mais solúvel que o sal: a 25 °C, 100 g de água dissolvem cerca de 210 g de sacarose, mas só 36 g de NaCl.',
    'Cavernas de calcário se formam por soluções: a água com CO₂ dissolve o CaCO₃ ao descer e o redeposita nas estalactites.',
    'O KMnO₄ é tão intensamente violeta que uma pitada colore litros de água — ótimo para enxergar diluições.',
    'Jogar sal nas estradas congeladas é crioscopia aplicada: a salmoura congela vários graus abaixo de zero.',
    'A panela de pressão eleva a pressão interna para ~1,4 atm e a água só ferve perto de 110 °C — o feijão cozinha mais rápido.',
    'Em La Paz, a 4.000 m, a água ferve a ~87 °C: massa demora muito mais para cozinhar.',
    'O etilenoglicol do radiador sobe o ponto de ebulição e desce o de congelamento da água do motor — dupla proteção coligativa.',
    'Peixes da Antártida produzem glicoproteínas anticongelantes que impedem o sangue de congelar a −1,9 °C.',
    'Conservar carne no sal e frutas no açúcar funciona por osmose: a água sai dos microrganismos, que desidratam.',
    'Beber água do mar desidrata porque ela é hipertônica em relação ao plasma: a osmose puxa água das células.',
    'A acetona (removedor de esmalte) evapora tão rápido que esfria a pele ao contato — sua pressão de vapor já é alta mesmo em temperatura ambiente.',
    'Água com gás gelada retém CO₂ muito melhor que morna: a solubilidade de gases cai com a temperatura — o oposto do que ocorre com a maioria dos sólidos.',
    'Peixes de água quente correm risco de asfixia térmica: a Lei de Henry faz o O₂ dissolvido cair bastante quando a água esquenta.',
  ],
};
